def create_abbreviations_dict():
    return {
        "ACARS": "Automatic Communications Addressing & Reporting System",
        "ACFT": "Aircraft",
        "ACR": "Air Carrier",
        "ADC": "Air Data Computer",
        "ADF": "Automatic Direction Finder",
        "ADG": "Air Driven Generator",
        "ADI": "Attitude Direction Indicator",
        "ADIZ": "Air Defense Identification Zone",
        "AERO": "Aeronautical",
        "AFB": "Air Force Base",
        "AFD": "Airport/Facility Directory",
        "AFDS": "Autopilot and Flight Director System",
        "AFSS": "Automated Flight Service Station",
        "AGL": "Above Ground Level",
        "AIM": "Aeronautical Information Manual",
        "ALS": "Automatic Landing System",
        "ALSF-1": "Standard 2400' Hi-Intensity Approach Lighting System With Sequenced Flashers (Cat I Config)",
        "ALSF-2": "Standard 2400' Hi-Intensity Approach Lighting System With Sequenced Flashers (Cat II Config)",
        "ALT": "Altitude",
        "ALTS": "Altitudes",
        "ALT(S)": "Altitude",
        "ALTDEV": "Altitude Deviation",
        "AM": "Ante Meridiem",
        "AMASS": "Airport Movement Area Safety System",
        "AMB": "Ambiguity",
        "AME": "Aviation Medical Examiner",
        "ANG": "Air National Guard",
        "APCH": "Approach",
        "APCHS": "Approaches",
        "APCHED": "Approached",
        "APCHING": "Approaching",
        "APCH (S,ED,ING)": "Approach",
        "APCH CTL": "Approach Control",
        "APPROX": "Approximately",
        "APU": "Auxiliary Power Unit",
        "ARFF": "Aircraft Rescue and Firefighting",
        "ARPT": "Airport",
        "ARPTS": "Airports",
        "ARPT(S)": "Airport",
        "ARR": "Arrival, Arrive",
        "ARSR": "Air Route Surveillance Radar",
        "ARTCC": "Air Route Traffic Control Center",
        "ARTS": "Automated Radar Terminal Systems",
        "ASAP": "As Soon As Possible",
        "ASOS": "Automated Surface Observation System",
        "AWOS": "Automated Weather Observing System",
        "ASDE": "Airport Surface Detection Equipment",
        "ASDE-X": "Airport Surface Detection Equipment, Model X",
        "ASOS/AWOS": "Automated Surface Observation Sys (Or Weather Observation Sys)",
        "ASR": "Airport Surveillance Radar",
        "ASRS": "Aviation Safety Reporting System",
        "ATC": "Air Traffic Control",
        "ATCT": "Airport Traffic Control Tower",
        "ATD": "Actual Time Of Departure",
        "ATIS": "Automatic Terminal Information Service",
        "ATOG": "Allowable Takeoff Gross Weight",
        "ATP": "Airline Transport Pilot Certificate",
        "ATR": "Airline Transport Rating",
        "ATTN": "Attention",
        "AUTH": "Authority/Authorized",
        "AUTO": "Automatic",
        "AUX": "Auxiliary",
        "AVG": "Average",
        "AVGAS": "Aviation Gasoline",
        "AWOS": "Automatic Weather Observing/Reporting System",
        "BAL": "Balance",
        "BALS": "Balances",
        "BALED": "Balanced",
        "BALING": "Balancing",
        "BAL (S,ED,ING)": "Balance",
        "BASE OPS": "Base Operations Office",
        "BC": "Back Course",
        "BCSTN": "Broadcast Station",
        "BFR": "Biennial Flight Review",
        "BKN": "Broken",
        "BRITE": "Bright Radar Indicator Tower Equipment",
        "BTWN": "Between",
        "BVLOS": "Beyond Visual Line Of Sight",
        "C": "Celsius",
        "CA": "Captain",
        "CAB": "Cabin Attendant",
        "CADC": "Central Air Data Computer",
        "CAP": "Civil Air Patrol",
        "CAPT": "Captain",
        "CARB": "Carburetor",
        "CAWS": "Central Aural Warning System",
        "CB": "Circuit Breaker",
        "CBO": "Community Based Organization",
        "CD": "Clearance Delivery",
        "CDI": "Course Deviation Indicator",
        "CDT": "Central Daylight Time",
        "CDU": "Control Display Unit",
        "CFI": "Certified Flight Instructor",
        "CFII": "Certified Flight Instructor - Instrument",
        "CFIT": "Controlled Flight Into Terrain",
        "CFR": "Crash Fire Rescue Equipment",
        "CGP": "Company Ground Personnel",
        "CHK": "Check",
        "CHKS": "Checks",
        "CHKED": "Checked",
        "CHKING": "Checking",
        "CHK (S,ED,ING)": "Check",
        "CIC": "Controller In Charge",
        "CLB": "Climb",
        "CLBS": "Climbs",
        "CLBED": "Climbed",
        "CLBING": "Climbing",
        "CLB (S,ED,ING)": "Climb",
        "CLR": "Clear",
        "CLRS": "Clears",
        "CLRED": "Cleared",
        "CLRING": "Clearing",
        "CLR (S,ED,ING)": "Clear",
        "CLRNC": "Clearance",
        "COA": "Certificate Of Authorization",
        "COM": "Communication",
        "COMS": "Communications",
        "COM(S)": "Communication",
        "CONFIG": "Configuration",
        "COORD": "Coordination",
        "COW": "Certificate Of Waiver",
        "CPC": "Certified Professional Controller",
        "CPCIT": "Certified Professional Controller-in-Training",
        "CPU": "Central Processing Unit",
        "CRM": "Cockpit Resource Management",
        "CRT": "Cathode Ray Tube",
        "CSD": "Constant Speed Drive",
        "CST": "Central Standard Time",
        "CTAF": "Common Traffic Advisory Frequency",
        "CTL": "Control",
        "CTLS": "Controls",
        "CTLED": "Controlled",
        "CTLING": "Controlling",
        "CTL (S,ED,ING)": "Control",
        "CTLR": "Controller",
        "CTLR'S": "Controller's",
        "CTLRS": "Controllers",
        "CTLR (S,'S)": "Controller",
        "CTR": "Center",
        "DAA": "Detect and Avoid",
        "DB": "Decibel",
        "DCU": "Data Control Unit",
        "DEG": "Degree",
        "DEGS": "Degrees",
        "DEG(S)": "Degree",
        "DEMO": "Demonstration",
        "DEP": "Departure",
        "DEPS": "Departures",
        "DEP(S)": "Departure",
        "DEPT": "Department",
        "DEPTS": "Departments",
        "DEPT(S)": "Department",
        "DEST": "Destination",
        "DESTS": "Destinations",
        "DEST(S)": "Destination",
        "DEV": "Deviation",
        "DEVS": "Deviations",
        "DEV(S)": "Deviation",
        "DF": "Direction Finder",
        "DFDR": "Digital Flight Data Recorder",
        "DFGS": "Digital Flight Guidance System",
        "DGPS": "Differential Global Positioning System",
        "DH": "Decision Height",
        "DISTR": "Distraction",
        "DME": "Distance Measuring Equipment",
        "DOD": "Department Of Defense",
        "DOE": "Department Of Energy",
        "DOT": "Department Of Transportation",
        "DSCNT": "Descent",
        "DSND": "Descend",
        "DSNDED": "Descended",
        "DSNDS": "Descends",
        "DSNDING": "Descending",
        "DSND (S,ED,ING)": "Descend",
        "DVFR": "Defense Visual Flight Rules",
        "E": "East",
        "EAC": "Expected Approach Clearance",
        "EAT": "Expected Approach Time",
        "EBND": "Eastbound",
        "ECAM": "Electronic Centralized Aircraft Monitoring",
        "ECOA": "Emergency Certificate Of Authorization",
        "EDT": "Eastern Daylight Time",
        "EFB": "Electronic Flight Bag",
        "EFIS": "Electronic Flight Instrument System",
        "EICAS": "Engine Indicating and Crew Alerting System",
        "ELT": "Emergency Locator Transmitter",
        "EMER": "Emergency",
        "EMERS": "Emergencies",
        "EMER(S)": "Emergency",
        "EMI": "Electromagnetic Interference",
        "EMS": "Emergency Medical Service",
        "ENG": "Engine",
        "ENGR": "Engineer",
        "ENRTE": "En Route",
        "EQUIP": "Equipment",
        "EROPS": "Extended Range Operations",
        "ESC": "Electronic Speed Control",
        "ETA": "Estimated Time Of Arrival",
        "ETD": "Estimated Time Of Departure",
        "ETOPS": "Extended Range Twin Operations",
        "EVAC": "Evacuate",
        "EVACS": "Evacuations",
        "EVACED": "Evacuated",
        "EVAC (S,ED)": "Evacuate/Evacuation",
        "EVAL": "Evaluate, Evaluation",
        "EXAM": "Examination",
        "F": "Fahrenheit",
        "FA": "Flight Attendant",
        "FA'S": "Flight Attendant's",
        "FAS": "Flight Attendants",
        "FA('S)": "Flight Attendant",
        "FAA": "Federal Aviation Administration",
        "FAC": "Facility",
        "FAF": "Final Approach Fix",
        "FAM": "Federal Air Marshal",
        "FAR": "Federal Aviation Regulation",
        "FARS": "Federal Aviation Regulations",
        "FAR(S)": "Federal Aviation Regulation",
        "FAX": "Facsimile",
        "FBO": "Fixed-Base Operator",
        "FCC": "Federal Communications Commission",
        "FCDU": "Flight Control Data Concentrator",
        "FCU": "Flight Control Unit",
        "FD": "Flight Director",
        "FDC": "Flight Data Center",
        "FE": "Flight Engineer",
        "FE'S": "Flight Engineer's",
        "FES": "Flight Engineers",
        "FE('S)": "Flight Engineer",
        "FGC": "Flight Guidance Computer",
        "FGS": "Flight Guidance Unit",
        "FIDO": "Flight Inspection District Office",
        "FL": "Flight Level",
        "FLC": "Flight Crew",
        "FLIP": "Flight Information Publication",
        "FLM": "Front Line Manager",
        "FLT": "Flight",
        "FM": "Frequency Modulation",
        "FMA": "Flight Mode Annunciator",
        "FMC": "Flight Management Computer",
        "FMGC": "Flight Management Guidance Computer",
        "FMGS": "Flight Management Guidance System",
        "FMS": "Flight Management System",
        "FO": "First Officer",
        "FOD": "Foreign Object Debris",
        "FOV": "Field Of View",
        "FPM": "Feet Per Minute",
        "FPV": "First Person View",
        "FREQ": "Frequency",
        "FREQS": "Frequencies",
        "FREQ(S)": "Frequency",
        "FRIA": "Federal Aviation Administration Recognized Identification Area",
        "FSDO": "Flight Standards District Office",
        "FSS": "Flight Service Station",
        "FSS'S": "Flight Service Station Specialist",
        "FSS('S)": "Flight Service Station Specialist",
        "FT": "Feet/Foot",
        "FYI": "For Your Information",
        "GA": "General Aviation",
        "GADO": "General Aviation District Office",
        "GAR": "Go Around",
        "GC": "Ground Control",
        "GCS": "Ground Control Station",
        "GHZ": "Gigahertz",
        "GMT": "Greenwich Mean Time (Zulu, UTC)",
        "GND": "Ground",
        "GNDS": "Ground",
        "GNDED": "Grounded",
        "GNDING": "Grounding",
        "GND(S,ED,ING)": "Ground",
        "GND SPD": "Ground Speed",
        "GNS": "Global Navigation System",
        "GOV": "Government",
        "GPS": "Global Positioning System",
        "GPWS": "Ground Proximity Warning System",
        "GS": "Glideslope (One Word)",
        "HDOF": "Handoff",
        "HDOFS": "Handoffs",
        "HDOF(S)": "Handoff",
        "HDG": "Heading",
        "HDGS": "Heading",
        "HDG(S)": "Heading",
        "HELI": "Helicopter",
        "HELIS": "Helicopters",
        "HELI(S)": "Helicopter",
        "HF": "High Frequency",
        "HGT": "Height",
        "HIALS": "High Intensity Approach Light System",
        "HIRL": "High Intensity Runway Lights",
        "HORIZ": "Horizontal",
        "HORIZLY": "Horizontally",
        "HORIZ(LY)": "Horizontal",
        "HQ": "Headquarters",
        "HR": "Hour",
        "HRS": "Hours",
        "HRLY": "Hourly",
        "HR (S,LY)": "Hour",
        "HSI": "Horizontal Situation Indicator",
        "HUD": "Head Up Display",
        "HVY": "Heavy",
        "HWY": "Highway",
        "HYD": "Hydraulic",
        "HZ": "Hertz",
        "IAF": "Initial Approach Fix",
        "IAP": "Instrument Approach Procedure",
        "IAS": "Indicated Air Speed",
        "IATA": "International Air Transport Association",
        "IAW": "In Accordance With",
        "ICAO": "International Civil Aviation Organization",
        "ID": "Identification",
        "IDENT": "Identify",
        "IF": "Intermediate Fix",
        "IFF": "Identification, Friend Or Foe",
        "IFR": "Instrument Flight Rules",
        "IFSS": "International Flight Service Station",
        "ILS": "Instrument Landing System",
        "IMC": "Instrument Meteorological Conditions",
        "IMU": "Inertial Measurement Unit",
        "INBND": "Inbound",
        "INC": "Incorporated",
        "INFO": "Information",
        "INOP": "Inoperative",
        "INS": "Inertial Navigation System",
        "INST": "Instrument",
        "INSTS": "Instruments",
        "INST(S)": "Instrument",
        "INTERFAC": "Interfacility",
        "INTERP": "Interpretation",
        "INTL": "International",
        "INTXN": "Intersection",
        "IOE": "Initial Operating Experience",
        "IRO": "International Relief Officer",
        "IRS": "Inertial Reference System",
        "IRU": "Inertial Reference Unit",
        "IRS/IRU": "Inertial Reference System/Unit",
        "ISDU": "Inertial Navigation Display Unit",
        "ISTR": "Instruct, Instructor",
        "KG": "Kilogram",
        "KHZ": "Kilohertz",
        "KIAS": "Knots Indicated Airspeed",
        "KM": "Kilometers",
        "KT": "Knot",
        "KTS": "Knots",
        "KT(S)": "Knot(S)",
        "KW": "Kilowatt",
        "LNDG": "Landing",
        "LWOC": "Landing Without Clearance",
        "LZ": "Landing Zone",
        "LNAV": "Lateral Navigation",
        "LNDG": "Landing",
        "LAT": "Latitude",
        "LB": "Pound",
        "L/R": "Left/Right (Directions)",
        "LTSS": "Less Than Standard Separation",
        "LTR": "Letter",
        "LOA": "Letter Of Agreement",
        "LED": "Light Emitting Diode",
        "LOS": "Line Of Sight",
        "LCD": "Liquid Crystal Display",
        "LIPO": "Lithium Polymer Battery",
        "LCL": "Local",
        "LC": "Local Control",
        "LC1": "Local Control 1",
        "LC2": "Local Control 2",
        "LOC": "Localizer",
        "LORAN": "Long Range Navigation",
        "LONG": "Longitude",
        "LAANC": "Low-Altitude Authorization and Notification Capability",
        "LF": "Low Frequency",
        "LIRL": "Low Intensity Runway Edge Lights",
        "LLWAS": "Low Level Wind Shear Alert System",
        "LLWS": "Low Level Wind Shear",
        "LMM": "Compass Locator At Instrument Landing System Middle Marker",
        "LOM": "Compass Locator At Instrument Landing System Outer Marker",
        "LUAW": "Line Up And Wait",
        "M": "Mach Number",
        "MAG": "Magnetic",
        "mAh": "Milliampere Hour",
        "MAINT": "Maintenance",
        "MALS": "Medium Intensity Approach Lighting System",
        "MALSF": "Medium Intensity Approach Lighting System With Sequenced Flashing Lights",
        "MALSR": "Medium Intensity Approach Lighting System With Runway Alignment Indicator Lights",
        "MAP": "Missed Approach Point",
        "MAX": "Maximum",
        "MB": "Millibars",
        "MCA": "Minimum Crossing Altitude",
        "MCAS": "Marine Corps Air Station",
        "MCP": "Mode Control Panel",
        "MDA": "Minimum Descent Altitude",
        "MDT": "Mountain Daylight Time",
        "MECH": "Mechanic",
        "MEA": "Minimum Enroute Altitude",
        "MEL": "Minimum Equipment List",
        "METRO": "Metropolitan",
        "MF": "Medium Frequency",
        "MFD": "Multi Function Display",
        "MFDU": "Multi Function Display Unit",
        "MGMNT": "Management",
        "MGR": "Manager",
        "MHZ": "Megahertz",
        "MI": "Mile",
        "MIKE, MIC": "Microphone",
        "MIL": "Military",
        "MIN": "Minute",
        "MINS": "Minutes",
        "MIN(S)": "Minute(S)",
        "MIRL": "Medium Intensity Runway Edge Lights",
        "MISC": "Miscellaneous",
        "MLS": "Microwave Landing System",
        "MM": "Middle Marker",
        "MOA": "Military Operating Area",
        "MOCA": "Minimum Obstruction Clearance Altitude",
        "MSA": "Minimum Safe Altitude",
        "MSAW": "Minimum Safe Altitude Warning",
        "MSG": "Message",
        "MSL": "Mean Sea Level",
        "MST": "Mountain Standard Time",
        "MTR": "Military Training Route",
        "MUNI": "Municipal",
        "MVA": "Minimum Vector Altitude",
        "MVFR": "Marginal Visual Flight Rules",
        "N": "North",
        "NAS": "Naval Air Station",
        "NASA": "National Aeronautics and Space Administration",
        "NATL": "National",
        "NAV (S,ING)": "Navigate, Navigation",
        "NAVAID": "Navigational Aid",
        "NBND": "Northbound",
        "NDB": "Nondirectional Radio Beacon",
        "NDB/DME": "Nondirectional Radio Beacon and Distance Measuring Equipment (Co-located)",
        "NCT": "North California Terminal Radar Approach Control Facility",
        "NFCT": "Non Federal Control Tower",
        "NFZ": "No-Fly Zone",
        "NM": "Nautical Mile",
        "NMAC": "Near Midair Collision",
        "NOAA": "National Oceanic and Atmospheric Administration",
        "NORAC": "No Radio Contact",
        "NORDO": "No Radio",
        "NOTAM": "Notice to Airmen / of Air Missions",
        "NTSB": "National Transportation Safety Board",
        "NWS": "National Weather Service",
        "N90": "New York Terminal Radar Approach Control Facility",
        "OAT": "Outside Air Temperature",
        "OJT": "On-The-Job Training",
        "OJTI": "On-The-Job Training Instructor",
        "OM": "Outer Marker",
        "ONS": "Omega Navigation System",
        "OP": "Operation",
        "OPS": "Operations",
        "OP(S)": "Operation(S)",
        "OPDEV": "Operational Deviation",
        "OPERROR": "Operational Error",
        "OSD": "On-Screen Display",
        "OTS": "Out Of Service",
        "OVCST": "Overcast",
        "PA": "Public Address",
        "PAPI": "Precision Approach Path Indicator",
        "PAR": "Precision Approach Radar",
        "PAX": "Passenger",
        "PCA": "Positive Control Area",
        "PCL": "Pilot Controlled Lighting",
        "PCU": "Power Control Unit",
        "PDC": "Pre Departure Clearance",
        "PDT": "Pacific Daylight Time",
        "PF": "Pilot Flying",
        "PIC": "Pilot In Command",
        "PIREP": "Pilot Report",
        "PIREPS": "Pilot Reports",
        "PIREP(S)": "Pilot Report",
        "PLT": "Pilot",
        "PLTS": "Pilots",
        "PLT'S": "Pilot's",
        "PLT (S,'S)": "Pilot",
        "PLTDEV": "Pilot Deviation",
        "PM": "Post Meridiem",
        "PMC": "Pilot Manipulating Controls",
        "PNF": "Pilot Not Flying",
        "POI": "Point Of Interest",
        "POS": "Position",
        "PRECIP": "Precipitation",
        "PROB": "Problem",
        "PROBS": "Problems",
        "PROB(S)": "Problem",
        "PROC": "Procedure",
        "PROCS": "Procedures",
        "PROC(S)": "Procedure",
        "PROP": "Propeller",
        "PROPS": "Propellers",
        "PROP(S)": "Propeller",
        "PROX": "Proximity",
        "PUB": "Publication",
        "PST": "Pacific Standard Time",
        "PVT": "Private",
        "PWR": "Power",
        "QFE": "Height Above Airport Elevation",
        "QRH": "Quick Reference Handbook",
        "RA": "Resolution Advisory",
        "RAIL": "Runway Alignment Indicator Lights",
        "RAPCON": "Radar Approach Control",
        "RAT": "Ram Air Turbine/Ram Air Temperature",
        "RC": "Radio Controlled",
        "RDMI": "Radio Direction Magnetic Indicator",
        "REF": "Reference",
        "REFS": "References",
        "REFING": "Referencing",
        "REF (S,ED,ING)": "Reference",
        "REG": "Regulation",
        "REGS": "Regulations",
        "REG(S)": "Regulation",
        "REIL": "Runway End Identifier Lights",
        "RESTR": "Restrict, Restricted, Restriction",
        "RF": "Radio Frequency",
        "RFI": "Radio Frequency Interference",
        "RID": "Remote ID (Identification)",
        "RMI": "Radio Magnetic Indicator",
        "RNAV": "Area Navigation",
        "RPA": "Remotely Piloted Aircraft",
        "RPAS": "Remotely Piloted Aircraft System",
        "RPIC": "Remote Pilot in Command",
        "RPM": "Revolutions Per Minute",
        "RPV": "Remotely Piloted Vehicle",
        "RTB": "Return to Base",
        "RTE": "Route",
        "RTF": "Ready to Fly",
        "RTH": "Return to Home",
        "RTL": "Return to Launch",
        "RTO": "Rejected Takeoff",
        "RVR": "Runway Visual Range",
        "RVV": "Runway Visibility Value",
        "RWY": "Runway",
        "RWYS": "Runways",
        "RWY(S)": "Runway(s)",
        "S": "South",
        "SAA": "Sense and Avoid",
        "SBND": "Southbound",
        "SELCAL": "Selective Calling",
        "SFL": "Sequenced Flashing Lights",
        "SID": "Standard Instrument Departure",
        "SIGMET": "Significant Meteorological Information",
        "SIT": "Situation",
        "SGI": "Special Government Interest",
        "SL": "Sea Level",
        "SM": "Statute Mile",
        "SO": "Second Officer",
        "SO'S": "Second Officer's",
        "SO(‘S)": "Second Officer",
        "SOP": "Standard Operating Procedure",
        "SOSC": "System Operations Support Center",
        "SPD": "Speed",
        "SPDS": "Speeds",
        "SPDING": "Speeding",
        "SPD (S,ING)": "Speed",
        "SPEC": "Specification",
        "SPECS": "Specifications",
        "SPEC(S)": "Specification",
        "STAB": "Stabilizer",
        "STAR": "Standard Terminal Arrival Route",
        "STARS": "Standard Terminal Automation Replacement System",
        "STD": "Standard",
        "STOL": "Short Takeoff and Landing",
        "SUAS": "Small Unmanned Aircraft System",
        "sUAS": "Small Unmanned Aircraft System",
        "SUPVR": "Supervisor",
        "SUPVRS": "Supervisors",
        "SUPVR(S)": "Supervisor",
        "SVC": "Service",
        "SVCS": "Service",
        "SVC(S)": "Service",
        "SVFR": "Special Visual Flight Rules",
        "SYS": "System",
        "TA": "Traffic Advisory",
        "TACAN": "Tactical Air Navigation Aid",
        "TAS": "True Air Speed",
        "TCA": "Terminal Control Area",
        "TCAS": "Traffic Alert and Collision Avoidance System",
        "TCAS II": "Traffic Alert and Collision Avoidance System",
        "TCAS (II)": "Traffic Alert and Collision Avoidance System",
        "TDZ": "Touchdown Zone",
        "TELCO": "Telephone Company",
        "TEMP": "Temperature",
        "TEMPS": "Temperature",
        "TEMP(S)": "Temperature",
        "TFC": "Traffic",
        "TFR": "Temporary Flight Restriction",
        "TIPH": "Taxi Into Position and Hold",
        "TKOF": "Takeoff",
        "TKOFS": "Takeoff",
        "TKOF(S)": "Takeoff",
        "TOC": "Top Of Climb",
        "TOD": "Top Of Descent",
        "TOGW": "Takeoff Gross Weight",
        "TR": "Visual Flight Rules Low Altitude Training Routes",
        "TRACON": "Terminal Radar Approach Control Facility",
        "TRNG": "Training",
        "TRSA": "Terminal Radar Service Area",
        "TRUST": "The Recreational UAS Safety Test",
        "TSTM": "Thunderstorm",
        "TSTMS": "Thunderstorms",
        "TSTM(S)": "Thunderstorm",
        "TURB": "Turbulence",
        "TWR": "Tower",
        "TWRS": "Towers",
        "TWR(S)": "Tower",
        "TX": "Transmitter",
        "TXWY": "Taxiway",
        "UA": "Unmanned Aircraft",
        "UAP": "Unidentified Anomalous Phenomena",
        "UAS": "Unmanned Aircraft System",
        "UASFM": "Unmanned Aircraft Systems Facility Map",
        "UAV": "Unmanned Aerial Vehicle",
        "UFO": "Unidentified Flying Object",
        "UHF": "Ultra High Frequency",
        "UNAUTH": "Unauthorized",
        "UNICOM": "Universal Communications, air-ground communication facility",
        "USA": "United States Army",
        "USAF": "United States Air Force",
        "USCG": "United States Coast Guard",
        "USMC": "United States Marine Corps",
        "USN": "United States Navy",
        "UTC": "Universal Time Coordinated (GMT, Zulu)",
        "UTM": "Unmanned Aircraft Systems Traffic Management",
        "VASI": "Visual Approach Slope Indicator",
        "VERTLY": "Vertically",
        "VERT(LY)": "Vertical",
        "VNAV": "Vertical Navigation",
        "VSTOL": "Vertical/Short Takeoff and Landing",
        "VHF": "Very High Frequency",
        "VFR": "Visual Flight Rules",
        "VHR": "Very High Frequency",
        "VLF": "Very Low Frequency",
        "VIS": "Visibility",
        "VLOS": "Visual Line of Sight",
        "VMC": "Visual Meteorological Conditions",
        "VO": "Visual Observer",
        "VOR": "Visual Flight Rules Omni-Directional Radio Range",
        "VOR/DME": "Visual Flight Rules Omni-Directional Radio Range and Distance Measuring Equipment (Co-located)",
        "VORTAC": "Visual Flight Rules Omni-Directional Radio Range and Tactical Air Navigation Aid (Co-Located)",
        "VR": "Visual Flight Rules Military Training Routes",
        "W": "West",
        "WAC": "World Aeronautical Chart",
        "WBND": "Westbound",
        "WKS": "Week",
        "WKLY": "Weekly",
        "WK (S,LY)": "Week",
        "WT": "Weight",
        "WT(S)": "Weight",
        "WX": "Weather",
        "XCOUNTRY": "Cross Country",
        "XING": "Crossing",
        "XMISSION": "Transmission",
        "XMIT": "Transmit",
        "XMITS": "Transmits",
        "XMITING": "Transmitting",
        "XMIT (S,TING)": "Transmit",
        "XPONDER": "Transponder",
        "XWIND": "Crosswind",
        "Z": "Zulu Time (UTC/GMT)"
    }


def create_double_counted_abbreviations_dict():
    return { "AC": ["Air Conditioning", "Alternating Current"], 
    "ATA": ["Actual Time Of Arrival", "Air Traffic Area"],
    "CAT": ["Category", "Clear Air Turbulence"],
    "EST": ["Eastern Standard Time", "Estimate, Estimation"]}


def create_icao_airports_dict():
    icao_airport_codes_dict = {}
    with open("airports.json", "r") as file:
        airport_data = json.load(file)
    for airport in airport_data:
        airport_code = airport_data[airport]["icao"]
        airport_name = airport_data[airport]["name"]
        icao_airport_codes_dict[airport_code] = airport_name
    return icao_airport_codes_dict

def create_iata_airports_dict():
    iata_airport_codes_dict = {}
    with open("airports.json", "r") as file:
        airport_data = json.load(file)
    for airport in airport_data:
        airport_code = airport_data[airport]["iata"]
        if airport_code == "" or airport_code is None:
            continue
        airport_name = airport_data[airport]["name"]
        iata_airport_codes_dict[airport_code] = airport_name
    return iata_airport_codes_dict
