services:
  - type: web
    name: asrs-dashboard
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PYTHON_API_URL
        value: http://localhost:5000
    healthCheckPath: / 