services:
  # Frontend - Node.js service
  - type: web
    name: asrs-frontend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PYTHON_API_URL
        value: https://asrs-api.onrender.com
    healthCheckPath: /

  # Backend API - Python service  
  - type: web
    name: asrs-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python api.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000
    healthCheckPath: /api/health 